[package]
name = "kimika"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kimika_grpc = { path = "../kimika_grpc" }
kimika_shared = { path = "../kimika_shared" }

bincode = "1.3.3"
clap = { version = "4.5.3", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version =  "1.36.0", features = ["rt-multi-thread", "macros", "sync", "time", "fs", "io-util"] }
tokio-stream = "0.1.15"
tonic = "0.11.0"
indicatif = "0.17.8"
toml = "0.8.12"
dirs = "5.0.1"
merge2 = "0.3.0" 
figment = { version = "0.10", features = ["toml"] }

[build-dependencies]
tonic-build = "0.11"
